# Generated by Django 4.1.6 on 2023-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_application_date_of_birth_application_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('UNDER_ASSESSMENT', 'UNDER_ASSESSMENT'), ('OFFER_LETTER_ISSUED', 'OFFER_LETTER_ISSUED'), ('CLEARED_FOR_ENROLLMENT', 'CLEARED_FOR_ENROLLMENT'), ('ENROLLMENT_COMPLETE', 'ENROLLMENT_COMPLETE')], default='PENDING', max_length=40),
        ),
    ]
