# Generated by Django 4.1.6 on 2023-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_applicationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='application',
            name='proposal',
        ),
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course / Qualification'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Organization'),
        ),
        migrations.AddField(
            model_name='application',
            name='fifth_form_school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fifth Form School'),
        ),
        migrations.AddField(
            model_name='application',
            name='fifth_form_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year in Fifth Form'),
        ),
        migrations.AddField(
            model_name='application',
            name='foundation_school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foundation School'),
        ),
        migrations.AddField(
            model_name='application',
            name='foundation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year in Foundation'),
        ),
        migrations.AddField(
            model_name='application',
            name='has_special_needs',
            field=models.BooleanField(default=False, verbose_name='Special Needs / Disability'),
        ),
        migrations.AddField(
            model_name='application',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instition'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_declared',
            field=models.BooleanField(default=False, verbose_name='Has been Declared'),
        ),
        migrations.AddField(
            model_name='application',
            name='last_saved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='application',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Major Field of Study'),
        ),
        migrations.AddField(
            model_name='application',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='month_year_started',
            field=models.DateField(blank=True, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='application',
            name='sixth_form_school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sixth Form School'),
        ),
        migrations.AddField(
            model_name='application',
            name='sixth_form_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year in Sixth Form'),
        ),
        migrations.AddField(
            model_name='application',
            name='sponsor_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sponsor Address'),
        ),
        migrations.AddField(
            model_name='application',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Sponsor Email'),
        ),
        migrations.AddField(
            model_name='application',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Sponsor'),
        ),
        migrations.AddField(
            model_name='application',
            name='sponsor_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sponsor Phone Number'),
        ),
        migrations.AddField(
            model_name='application',
            name='sponsor_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('sponsored', 'Sponsored'), ('private_with_concession', 'Private with Concession (staff)')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='third_form_school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Third Form School'),
        ),
        migrations.AddField(
            model_name='application',
            name='third_form_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year in Third Form'),
        ),
        migrations.AddField(
            model_name='application',
            name='year_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year Start'),
        ),
        migrations.AddField(
            model_name='application',
            name='year_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year Start'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('Submitted', 'Submitted')], default='draft', max_length=40, verbose_name='State of Application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo of Applicant'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('dr', 'Dr')], max_length=3, null=True, verbose_name='Title'),
        ),
    ]
