# Generated by Django 4.1.6 on 2023-05-05 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0009_remove_application_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, to_field='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='month_year_started',
            field=models.DateField(blank=True, null=True, verbose_name='Month/Year Started'),
        ),
    ]
