# Generated by Django 4.1.6 on 2023-05-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_prerequisite_prerequisite_and_more'),
        ('admission', '0010_application_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='selected_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='courses.course', to_field='code', verbose_name='Course Applying For'),
            preserve_default=False,
        ),
    ]
