# Generated by Django 4.1.6 on 2023-06-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_alter_application_current_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='edit_section',
            field=models.CharField(choices=[('personal_details', 'Personal Details'), ('sponsor_details', 'Sponsor Details'), ('education_background', 'Education Background'), ('employment_history', 'Employment History'), ('declaration', 'Declaration')], default='personal_details', max_length=40, verbose_name='The section that is on edit by user'),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_section',
            field=models.CharField(choices=[('personal_details', 'Personal Details'), ('sponsor_details', 'Sponsor Details'), ('education_background', 'Education Background'), ('employment_history', 'Employment History'), ('declaration', 'Declaration')], default='personal_details', max_length=40, verbose_name='The furthest section that the user has reached before submitting'),
        ),
    ]
