# Generated by Django 4.1.6 on 2023-07-19 06:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0016_application_edit_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipLetter',
            fields=[
                ('file', models.FileField(upload_to='documents/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
