# Generated by Django 4.1.6 on 2023-07-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_alter_sponsorshipletter_application_hsdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_school_documents', to='admission.application'),
        ),
    ]
