# Generated by Django 4.1.6 on 2023-07-24 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_remove_application_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instition')),
                ('course', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course / Qualification')),
                ('year_start', models.IntegerField(blank=True, null=True, verbose_name='Year Started')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='Year Ended')),
                ('major', models.CharField(blank=True, max_length=255, null=True, verbose_name='Major Field of Study')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='admission.application')),
            ],
        ),
    ]
