# Generated by Django 4.1.6 on 2023-07-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_institution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution',
            new_name='TertiaryQualification',
        ),
    ]
