# Generated by Django 4.1.6 on 2023-07-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0023_rename_institution_tertiaryqualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tertiaryqualification',
            name='name',
        ),
        migrations.AddField(
            model_name='tertiaryqualification',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Institution'),
        ),
        migrations.AlterField(
            model_name='tertiaryqualification',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_qualifications', to='admission.application'),
        ),
    ]
