# Generated by Django 4.1.6 on 2023-08-17 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_remove_tertiaryqualification_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TQDocument',
            fields=[
                ('file', models.FileField(upload_to='documents/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(choices=[('transcript', 'Acadmic Transcript'), ('certificate', 'Academic Certificate')], max_length=20, verbose_name='Document Type')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='admission.tertiaryqualification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
