# Generated by Django 4.1.6 on 2023-10-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_tqdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='current_organization',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='application',
            name='month_year_started',
        ),
    ]
