# Generated by Django 4.1.6 on 2023-10-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_remove_application_current_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization / Company')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('month_year_started', models.DateField(blank=True, null=True, verbose_name='Month/Year Started')),
                ('month_year_ended', models.DateField(blank=True, null=True, verbose_name='Month/Year Ended')),
                ('is_current', models.BooleanField(blank=True, null=True, verbose_name='Current Employment')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_employments', to='admission.application')),
            ],
        ),
    ]
