# Generated by Django 4.1.6 on 2023-10-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0027_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='month_year_ended',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Month/Year Ended'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='month_year_started',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Month/Year Started'),
        ),
    ]
