# Generated by Django 4.1.6 on 2023-11-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0030_remove_application_application_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='fifth_form_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year in Fifth Form'),
        ),
        migrations.AlterField(
            model_name='application',
            name='foundation_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year in Foundation'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sixth_form_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year in Sixth Form'),
        ),
        migrations.AlterField(
            model_name='application',
            name='third_form_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year in Third Form'),
        ),
    ]
