# Generated by Django 4.1.6 on 2023-11-21 23:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0032_remove_application_edit_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='application',
            name='citizenship',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Citizenship'),
        ),
        migrations.AddField(
            model_name='application',
            name='constituency',
            field=models.CharField(blank=True, choices=[('Aoke-Langalanga', 'Aoke-Langalanga'), ('Baegu-Asifola', 'Baegu-Asifola'), ('Central Guadalcanal', 'Central Guadalcanal'), ('Central Honiara', 'Central Honiara'), ("Central Kwara'ae", "Central Kwara'ae"), ('Central Makira', 'Central Makira'), ('East ꞌAreꞌare', 'East ꞌAreꞌare'), ('East Central Guadalcanal', 'East Central Guadalcanal'), ('East Choiseul', 'East Choiseul'), ('East Guadalcanal', 'East Guadalcanal'), ('East Honiara', 'East Honiara'), ('East Kwaio', 'East Kwaio'), ('East Makira', 'East Makira'), ('East Malaita', 'East Malaita'), ('Fataleka', 'Fataleka'), ('Gao-Bugotu', 'Gao-Bugotu'), ('Gizo-Kolombangara', 'Gizo-Kolombangara'), ('Hograno-Kia-Havulei', 'Hograno-Kia-Havulei'), ('Lau Mbaelelea', 'Lau Mbaelelea'), ('Malaita Outer Islands', 'Malaita Outer Islands'), ('Maringe-Kokota', 'Maringe-Kokota'), ('Marovo', 'Marovo'), ('Nggella', 'Nggella'), ('North East Guadalcanal', 'North East Guadalcanal'), ('North Guadalcanal', 'North Guadalcanal'), ('North Malaita', 'North Malaita'), ('North New Georgia', 'North New Georgia'), ('North Vella La Vella', 'North Vella La Vella'), ('North West Choiseul', 'North West Choiseul'), ('North West Guadalcanal', 'North West Guadalcanal'), ('Rannogga-Simbo', 'Rannogga-Simbo'), ('Rennell Bellona', 'Rennell Bellona'), ('Savo-Russells', 'Savo-Russells'), ('Shortlands', 'Shortlands'), ('South Choiseul', 'South Choiseul'), ('South Guadalcanal', 'South Guadalcanal'), ('Small Malaita', 'Small Malaita'), ('South New Georgia-Rendova-Tetepare', 'South New Georgia-Rendova-Tetepare'), ('South Vella La Vella', 'South Vella La Vella'), ('Temotu Nende', 'Temotu Nende'), ('Temotu Pele', 'Temotu Pele'), ('Temotu Vatud', 'Temotu Vatud'), ('Ugi-Ulawa', 'Ugi-Ulawa'), ('West ꞌAreꞌare', 'West ꞌAreꞌare'), ('West Guadalcanal', 'West Guadalcanal'), ('West Honiara', 'West Honiara'), ('West Kwaio', 'West Kwaio'), ("West Kwara'ae", "West Kwara'ae"), ('West New Georgia - Vona Vona', 'West New Georgia - Vona Vona'), ('West Makira', 'West Makira')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_postal',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Contact (Postal)'),
        ),
        migrations.AddField(
            model_name='application',
            name='country_of_birth',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country of Birth'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_address',
            field=models.TextField(blank=True, null=True, verbose_name='Guardian Address'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Guardian'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Guardian Phone Number'),
        ),
        migrations.AddField(
            model_name='application',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='application',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AddField(
            model_name='application',
            name='province',
            field=models.CharField(blank=True, choices=[('Guadalcanal', 'Guadalcanal'), ('Western', 'Western'), ('Temotu', 'Temotu'), ('Malaita', 'Malaita'), ('Isabel', 'Isabel'), ('Choiseul', 'Choiseul'), ('Makira', 'Makira'), ('Renbel', 'Renbel'), ('Central', 'Central')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telephone Number'),
        ),
        migrations.AddField(
            model_name='application',
            name='ward',
            field=models.CharField(blank=True, choices=[('Aoke-Langalanga', 'Aoke-Langalanga'), ('Baegu-Asifola', 'Baegu-Asifola'), ('Central Guadalcanal', 'Central Guadalcanal'), ('Central Honiara', 'Central Honiara'), ("Central Kwara'ae", "Central Kwara'ae"), ('Central Makira', 'Central Makira'), ('East ꞌAreꞌare', 'East ꞌAreꞌare'), ('East Central Guadalcanal', 'East Central Guadalcanal'), ('East Choiseul', 'East Choiseul'), ('East Guadalcanal', 'East Guadalcanal'), ('East Honiara', 'East Honiara'), ('East Kwaio', 'East Kwaio'), ('East Makira', 'East Makira'), ('East Malaita', 'East Malaita'), ('Fataleka', 'Fataleka'), ('Gao-Bugotu', 'Gao-Bugotu'), ('Gizo-Kolombangara', 'Gizo-Kolombangara'), ('Hograno-Kia-Havulei', 'Hograno-Kia-Havulei'), ('Lau Mbaelelea', 'Lau Mbaelelea'), ('Malaita Outer Islands', 'Malaita Outer Islands'), ('Maringe-Kokota', 'Maringe-Kokota'), ('Marovo', 'Marovo'), ('Nggella', 'Nggella'), ('North East Guadalcanal', 'North East Guadalcanal'), ('North Guadalcanal', 'North Guadalcanal'), ('North Malaita', 'North Malaita'), ('North New Georgia', 'North New Georgia'), ('North Vella La Vella', 'North Vella La Vella'), ('North West Choiseul', 'North West Choiseul'), ('North West Guadalcanal', 'North West Guadalcanal'), ('Rannogga-Simbo', 'Rannogga-Simbo'), ('Rennell Bellona', 'Rennell Bellona'), ('Savo-Russells', 'Savo-Russells'), ('Shortlands', 'Shortlands'), ('South Choiseul', 'South Choiseul'), ('South Guadalcanal', 'South Guadalcanal'), ('Small Malaita', 'Small Malaita'), ('South New Georgia-Rendova-Tetepare', 'South New Georgia-Rendova-Tetepare'), ('South Vella La Vella', 'South Vella La Vella'), ('Temotu Nende', 'Temotu Nende'), ('Temotu Pele', 'Temotu Pele'), ('Temotu Vatud', 'Temotu Vatud'), ('Ugi-Ulawa', 'Ugi-Ulawa'), ('West ꞌAreꞌare', 'West ꞌAreꞌare'), ('West Guadalcanal', 'West Guadalcanal'), ('West Honiara', 'West Honiara'), ('West Kwaio', 'West Kwaio'), ("West Kwara'ae", "West Kwara'ae"), ('West New Georgia - Vona Vona', 'West New Georgia - Vona Vona'), ('West Makira', 'West Makira')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='sponsor_address',
            field=models.TextField(blank=True, null=True, verbose_name='Sponsor Address'),
        ),
    ]
