# Generated by Django 4.1.6 on 2023-11-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0034_alter_application_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical/', verbose_name='Medical Report'),
        ),
    ]
