# Generated by Django 4.1.6 on 2023-11-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0035_application_medical_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='province',
            field=models.CharField(blank=True, choices=[('Guadalcanal', 'Guadalcanal'), ('Western', 'Western'), ('Temotu', 'Temotu'), ('Malaita', 'Malaita'), ('Isabel', 'Isabel'), ('Choiseul', 'Choiseul'), ('Makira/Ulawa', 'Makira/Ulawa'), ('Rennell/Bellona', 'Rennell/Bellona'), ('Central', 'Central')], max_length=150, null=True),
        ),
    ]
