# Generated by Django 4.1.6 on 2023-11-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0036_alter_application_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=5, null=True, verbose_name='Title'),
        ),
    ]
