# Generated by Django 4.1.6 on 2023-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0039_remove_application_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='application',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], max_length=100, null=True, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sponsor_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('sponsored', 'Sponsored'), ('private_with_concession', 'Private with Concession (staff)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=100, null=True, verbose_name='Title'),
        ),
    ]
