# Generated by Django 4.1.6 on 2023-11-30 15:19

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0040_alter_application_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='citizenship',
            field=django_countries.fields.CountryField(blank=True, max_length=150, null=True, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='application',
            name='country_of_birth',
            field=django_countries.fields.CountryField(blank=True, max_length=150, null=True, verbose_name='Country of Birth'),
        ),
    ]
