# Generated by Django 4.1.6 on 2023-12-04 00:37

import admission.utils.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0041_alter_application_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deposit_slip',
            field=models.FileField(blank=True, null=True, upload_to=admission.utils.upload_path.upload_path, verbose_name='Deposit Slip'),
        ),
        migrations.AlterField(
            model_name='application',
            name='letter_of_offer',
            field=models.FileField(blank=True, null=True, upload_to=admission.utils.upload_path.upload_path, verbose_name='Letter of Offer'),
        ),
        migrations.AlterField(
            model_name='application',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to=admission.utils.upload_path.upload_path, verbose_name='Medical Report'),
        ),
        migrations.AlterField(
            model_name='application',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=admission.utils.upload_path.upload_path, verbose_name='Receipt'),
        ),
    ]
