# Generated by Django 4.1.6 on 2023-12-04 08:00

import admission.models.document
import admission.utils.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0042_alter_application_deposit_slip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sponsorship_letter',
            field=models.FileField(blank=True, null=True, upload_to=admission.utils.upload_path.upload_path, verbose_name='Sponsorship Letter'),
        ),
        migrations.AlterField(
            model_name='hsdocument',
            name='file',
            field=models.FileField(upload_to=admission.models.document.document_upload_path),
        ),
        migrations.AlterField(
            model_name='tqdocument',
            name='file',
            field=models.FileField(upload_to=admission.models.document.document_upload_path),
        ),
        migrations.DeleteModel(
            name='SponsorshipLetter',
        ),
    ]
