# Generated by Django 4.1.6 on 2023-12-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0043_application_sponsorship_letter_alter_hsdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_submitted',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Submission Date'),
        ),
    ]
