# Generated by Django 4.1.6 on 2023-12-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0045_alter_application_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Student ID'),
        ),
    ]
