version: '3'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000

  nginx:
    image: nginx:1.24.0
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles/:/usr/share/nginx/html/
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - web


