version: '3'

services:
  app:
    build: .
    image: admission-app
    command: >
      bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres:15.3
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  proxy:
    image: nginx:1.24.0
    volumes:
      - /home/sinu_admin/admissions/certbot/conf/:/etc/nginx/ssl/:ro
      - /home/sinu_admin/admissions/certbot/www/:/var/www/certbot/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles/:/usr/share/nginx/html/:ro
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./.env
    depends_on:
      - app
    restart: always

volumes:
  postgres_data: