# Generated by Django 4.1.6 on 2023-04-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='abbr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School Abbreviation'),
        ),
    ]
