# Generated by Django 4.1.6 on 2023-05-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_school_abbr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
    ]
