# Generated by Django 4.1.6 on 2023-04-26 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Course Code')),
                ('title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('qualification_level', models.CharField(choices=[('Degree', 'Degree'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Postgraduate Diploma', 'Postgraduate Diploma'), ('Masters', 'Mast')], default='Certificate', max_length=50)),
                ('description', models.TextField(verbose_name='Course Description')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_mode', models.CharField(choices=[('DFL', 'DFL'), ('On-Campus', 'On-Campus')], default='On-Campus', max_length=10, verbose_name='Offered Mode')),
                ('duration_type', models.CharField(choices=[('Year', 'Year'), ('Month', 'Month')], max_length=5, verbose_name='Duration Type')),
                ('duration_length', models.IntegerField(verbose_name='Duration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
