# Generated by Django 4.1.6 on 2023-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_credit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_core_units',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Core Units'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_elective_units',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Elective Units'),
        ),
    ]
