# Generated by Django 4.1.6 on 2023-05-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_prerequisite_prerequisite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.courseunit', verbose_name='Prerequisite'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='prerequisite_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_prerequisites', to='courses.prerequisitegroup'),
        ),
    ]
