# Generated by Django 4.1.6 on 2023-02-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbasubmission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(to='mbasubmission.document', verbose_name='Documents'),
        ),
    ]
