# Generated by Django 4.1.6 on 2023-03-17 02:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mbasubmission', '0007_application_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mbasubmission.application')),
            ],
        ),
    ]
