name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: SSH into Host Server
        uses: appleboy/ssh-action@master
        with:
          host: 202.1.168.144
          username: oeadmin
          password: kc03@4dm1n
          port: 2220
          scripts: |
            cd /app
            git pull origin main
            docker-compose build
            docker-compose up -d




