# Generated by Django 4.1.6 on 2023-04-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_length',
            field=models.IntegerField(default=3, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duration_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Month', 'Month')], default='year', max_length=5, verbose_name='Duration Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='offered_mode',
            field=models.CharField(choices=[('DFL', 'DFL'), ('On-Campus', 'On-Campus')], default='On-Campus', max_length=10, verbose_name='Offered Mode'),
        ),
        migrations.DeleteModel(
            name='OfferedCourse',
        ),
    ]
