# Generated by Django 4.1.6 on 2023-04-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_offered_mode_course_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='campus',
            field=models.CharField(choices=[('Kukum', 'Kukum'), ('Marine', 'Marine'), ('Panatina', 'Panatina')], default='Kukum', max_length=10, verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_length',
            field=models.FloatField(verbose_name='Duration'),
        ),
    ]
