# Generated by Django 4.1.6 on 2023-04-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='campus',
            field=models.CharField(blank=True, choices=[('kukum', 'kukum'), ('marine', 'marine'), ('panatina', 'panatina')], max_length=10, null=True, verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('year', 'year'), ('month', 'month'), ('week', 'week')], max_length=5, null=True, verbose_name='Duration Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='qualification_level',
            field=models.CharField(blank=True, choices=[('degree', 'degree'), ('pre-degree', 'pre-degree'), ('certificate', 'certificate'), ('advanced certificate', 'advanced certificate'), ('diploma', 'diploma'), ('pre-diploma', 'pre-diploma'), ('postgraduate diploma', 'postgraduate diploma'), ('master degree', 'master degree')], max_length=50, null=True),
        ),
    ]
