# Generated by Django 4.1.6 on 2023-05-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_period', models.CharField(max_length=20, verbose_name='Study Period')),
            ],
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('core', 'Core'), ('elective', 'Elective')], max_length=10, null=True, verbose_name='Unit Type')),
                ('credit_points', models.IntegerField(blank=True, null=True, verbose_name='Credit Points')),
                ('offer_year', models.CharField(blank=True, choices=[('year_1', 'Year 1'), ('year_2', 'Year 2'), ('year_3', 'Year 3'), ('year_4', 'Year 4')], max_length=10, null=True, verbose_name='Offer Year')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Select Course')),
                ('study_period', models.ManyToManyField(blank=True, to='courses.studyperiod', verbose_name='Study Period')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.unit', verbose_name='Select Unit')),
            ],
            options={
                'unique_together': {('unit', 'course')},
            },
        ),
    ]
