# Generated by Django 4.1.6 on 2023-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_studyperiod_courseunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_points',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Credit Points'),
        ),
    ]
