# Generated by Django 4.1.6 on 2023-05-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_total_core_units_course_total_elective_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseunit',
            name='study_period',
            field=models.ManyToManyField(blank=True, to='courses.studyperiod'),
        ),
    ]
