# Generated by Django 4.1.6 on 2023-05-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_courseunit_study_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrerequisiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Prerequisite Group (name format - [Course Code]-[Unit Code]-[1])')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_groups', to='courses.courseunit')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseunit', verbose_name='Prerequisite')),
                ('prerequisite_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.prerequisitegroup')),
            ],
        ),
    ]
