# Generated by Django 4.1.6 on 2023-05-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_prerequisitegroup_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereqs', to='courses.courseunit', verbose_name='Prerequisite'),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('prerequisite_group', 'prerequisite')},
        ),
    ]
